#!/bin/bash

set -eo pipefail

branch=$1
version=$2

if [ "$branch" == "master" ] ; then
	git clone https://github.com/trealla-prolog/trealla
	cd trealla
	if [ "$version" == "latest" ] ; then
		git checkout master
	else
		git fetch --all --tags
		git checkout "$version"
	fi
elif [ "$branch" == "devel" ] ; then
	git clone https://github.com/trealla-prolog/trealla
	cd trealla
	if [ "$version" == "latest" ] ; then
		git checkout devel
	else
		git fetch --all --tags
		git checkout "$version"
	fi
else
	exit 1
fi

sudo apt-get install -y libssl-dev
sudo apt-get install -y libreadline-dev

make clean && make
sudo ln -s "$PWD/tpl" /usr/local/bin/tpl
