#!/bin/bash

set -eo pipefail

branch=$1
version=$2

brew install coreutils

if [ "$branch" == "master" ] ; then
	if [ "$version" == "latest" ] ; then
		git clone https://github.com/infradig/trealla.git
		cd trealla
		git checkout master
	else
		git clone https://github.com/infradig/trealla.git
		cd trealla
		git fetch --all --tags
		git checkout "$version"
	fi
elif [ "$branch" == "devel" ] ; then
	if [ "$version" == "latest" ] ; then
		git clone https://github.com/infradig/trealla.git
		cd trealla
		git checkout devel
	else
		git clone https://github.com/infradig/trealla.git
		cd trealla
		git fetch --all --tags
		git checkout "$version"
	fi
else
	exit 1
fi

brew install make
brew install openssl
brew install readline

export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include"

gmake clean && gmake NOLDLIBS=1 NOSSL=1
sudo ln -s "$PWD/tpl" /usr/local/bin/tpl
