name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Install Trealla ProLog
        uses: logtalk-actions/setup-trealla-prolog@master
        with:
          trealla-prolog-branch: devel
          trealla-prolog-version: latest
      - name: Run trivial sanity test
        run: tpl -g halt
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: git
          logtalk-tool-dependencies: false
      - name: Run Logtalk aliases example tests
        run: cd "$LOGTALKUSER/examples/aliases" && logtalk_tester -p trealla
